# Exported from Render on 2026-03-14T06:09:32Z
version: "1"
projects:
- name: SOS-Connect
  environments:
  - name: Production
    services:
    - type: web
      name: SOS-Connect
      runtime: python
      repo: https://github.com/samruddhibawaskar097-ship-it/SOSConnect-Backend
      plan: free
      envVars:
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: TWILIO_MESSAGING_SERVICE_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      region: singapore
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn app:app
      autoDeployTrigger: commit
